#!/usr/bin/env python3
"""Build chronological + by-category indices for `errors/`.

See `errors/README.md` for the error-log schema.

Walks `errors/*.md`, parses YAML frontmatter, emits:

- `errors/INDEX.md` — chronological table.
- `errors/BY-CATEGORY.md` — grouped by category, then
  subcategory.

Both files are auto-generated; humans should not edit. Run after
adding or modifying any error file.

Pure stdlib; no PyYAML dependency — the frontmatter we use is
simple enough to parse with `yaml` if available, else a small
hand-parser. We try `yaml` first.
"""

from __future__ import annotations

import sys
from collections import defaultdict
from pathlib import Path

try:
    import yaml  # type: ignore
    _HAVE_YAML = True
except ImportError:
    _HAVE_YAML = False


HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent.parent
ERRORS = ROOT / "errors"
INDEX_OUT = ERRORS / "INDEX.md"
BY_CATEGORY_OUT = ERRORS / "BY-CATEGORY.md"


# ---------- frontmatter parsing ----------


def _read_frontmatter(path: Path) -> dict:
    """Extract the `---`…`---` block at the top of `path` and parse
    it as YAML. Returns {} if no frontmatter."""
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---"):
        return {}
    parts = text.split("---", 2)
    if len(parts) < 3:
        return {}
    fm_text = parts[1]
    if _HAVE_YAML:
        try:
            data = yaml.safe_load(fm_text) or {}
            if not isinstance(data, dict):
                return {}
            return data
        except yaml.YAMLError as e:
            print(f"[ERROR] {path.name}: yaml parse failed: {e}",
                  file=sys.stderr)
            return {}
    return _hand_parse(fm_text)


def _hand_parse(text: str) -> dict:
    """Tiny YAML subset for the error-log frontmatter — flat
    key:value pairs and lists. Used only when PyYAML is missing."""
    out: dict = {}
    cur_key: str | None = None
    cur_list: list | None = None
    for raw in text.splitlines():
        line = raw.rstrip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("  - "):
            if cur_list is not None:
                cur_list.append(line[4:].strip().strip("'\""))
            continue
        if line.startswith("  ") and cur_key:
            # Sub-key under the current top-level key.
            sub = line.strip()
            if ":" in sub:
                k, v = sub.split(":", 1)
                out.setdefault(cur_key, {})
                if isinstance(out[cur_key], dict):
                    out[cur_key][k.strip()] = v.strip().strip("'\"")
            continue
        if ":" in line:
            k, _, v = line.partition(":")
            k = k.strip()
            v = v.strip()
            cur_key = k
            cur_list = None
            if not v:
                # Could be either a list or a sub-mapping; default
                # to list mode and switch on first sub-element.
                out[k] = []
                cur_list = out[k]
            else:
                out[k] = v.strip("'\"")
    return out


# ---------- collection ----------


def collect_errors() -> list[dict]:
    """Return every error file's frontmatter + filename, sorted by
    id (chronological)."""
    out: list[dict] = []
    for path in sorted(ERRORS.glob("*.md")):
        if path.name in ("README.md", "INDEX.md", "BY-CATEGORY.md"):
            continue
        fm = _read_frontmatter(path)
        if not fm:
            print(f"[WARN] {path.name}: no parseable frontmatter; "
                  "skipping", file=sys.stderr)
            continue
        fm["_path"] = path.name
        out.append(fm)
    return out


# ---------- summary extraction ----------


def _first_input_line(path_name: str) -> str:
    """Read the body, find the `## Input` section, return its
    first non-empty line. Used as a one-line summary for the
    chronological index."""
    path = ERRORS / path_name
    text = path.read_text(encoding="utf-8")
    parts = text.split("---", 2)
    if len(parts) < 3:
        body = text
    else:
        body = parts[2]
    in_input = False
    for raw in body.splitlines():
        line = raw.strip()
        if line.startswith("## Input"):
            in_input = True
            continue
        if in_input:
            if line.startswith("##"):
                break
            if line:
                return line[:100]
    return ""


# ---------- index rendering ----------


def _g(fm: dict, key: str, default: str = "?") -> str:
    val = fm.get(key, default)
    if val is None:
        return default
    return str(val)


def render_chronological(errors: list[dict]) -> str:
    out: list[str] = []
    out.append("# `errors/INDEX.md` — chronological log\n")
    out.append("*Auto-generated by `.claude/skills/error-log/"
               "build_index.py`. Do not hand-edit; re-run after "
               "adding or modifying errors.*\n")
    out.append(f"Total entries: **{len(errors)}**\n")
    counts = defaultdict(int)
    for e in errors:
        counts[_g(e, "status")] += 1
    if counts:
        out.append("Status: " + ", ".join(
            f"`{s}`={n}" for s, n in sorted(counts.items())))
        out.append("")
    out.append("| id | date | category | subcategory | severity | "
               "status | disposition | summary |")
    out.append("|----|------|----------|-------------|----------|"
               "--------|-------------|---------|")
    for fm in errors:
        path_name = fm["_path"]
        summary = _first_input_line(path_name)
        out.append(
            f"| [`{_g(fm, 'id')}`]({path_name}) "
            f"| {_g(fm, 'date')} "
            f"| `{_g(fm, 'category')}` "
            f"| `{_g(fm, 'subcategory')}` "
            f"| {_g(fm, 'severity')} "
            f"| {_g(fm, 'status')} "
            f"| {_g(fm, 'disposition')} "
            f"| {summary} |"
        )
    out.append("")
    return "\n".join(out)


def render_by_category(errors: list[dict]) -> str:
    grouped: dict[str, dict[str, list[dict]]] = defaultdict(
        lambda: defaultdict(list))
    for fm in errors:
        cat = _g(fm, "category", "uncategorised")
        sub = _g(fm, "subcategory", "—")
        grouped[cat][sub].append(fm)

    out: list[str] = []
    out.append("# `errors/BY-CATEGORY.md` — grouped\n")
    out.append("*Auto-generated by `.claude/skills/error-log/"
               "build_index.py`. Do not hand-edit; re-run after "
               "adding or modifying errors.*\n")
    out.append(f"Total entries: **{len(errors)}** "
               f"across **{len(grouped)}** categories.\n")
    out.append("## Category counts\n")
    out.append("| category | entries |")
    out.append("|----------|---------|")
    for cat in sorted(grouped):
        n = sum(len(v) for v in grouped[cat].values())
        out.append(f"| `{cat}` | {n} |")
    out.append("")
    for cat in sorted(grouped):
        out.append(f"## `{cat}`\n")
        for sub in sorted(grouped[cat]):
            entries = grouped[cat][sub]
            out.append(f"### `{sub}` ({len(entries)})\n")
            for fm in entries:
                path_name = fm["_path"]
                summary = _first_input_line(path_name)
                out.append(
                    f"- [`{_g(fm, 'id')}`]({path_name}) "
                    f"({_g(fm, 'severity')}, "
                    f"{_g(fm, 'status')}, "
                    f"{_g(fm, 'disposition')}) — {summary}"
                )
            out.append("")
    return "\n".join(out)


# ---------- main ----------


def main() -> int:
    if not ERRORS.exists():
        print(f"[ERROR] {ERRORS} does not exist", file=sys.stderr)
        return 1
    errors = collect_errors()
    if not errors:
        print("No errors found; nothing to index.", file=sys.stderr)
        return 0
    INDEX_OUT.write_text(render_chronological(errors), encoding="utf-8")
    BY_CATEGORY_OUT.write_text(render_by_category(errors), encoding="utf-8")
    print(f"Indexed {len(errors)} error file(s).")
    print(f"  → {INDEX_OUT.relative_to(ROOT)}")
    print(f"  → {BY_CATEGORY_OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
