"""Step D: mechanical merge + typeset — book.md + glosses.tsv → PDF.

Pure function of its inputs: no judgement, only placement and layout.
- Each glosses.tsv row is anchored at the FIRST word-boundary
  occurrence of its surface inside its block (chapter-scope dedup:
  one gloss per lemma per chunk — see FRD § R4/D).
- The gloss renders under the word (ruby-style stack); rows with
  source=prior get a dashed underline (FRD gap policy).
- [^N] markers become typst footnotes carrying the footnote block's
  text (typst renumbers; original number is preserved in the text).
- Page geometry / fonts / gloss styling are CLI settings: changing
  them re-runs D only.

Usage: python3 render.py --book ghamoyan --chunk ch2 [--paper a5]
       [--size 10] [--no-compile]
"""
from __future__ import annotations

import argparse
import csv
import re
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from common import Block, md_runs, parse_book_md  # noqa: E402

# Armenian LETTERS only — the block range [԰-֏] would also match
# punctuation like ՝ and wrongly veto anchors such as "փոխ.՝"
ARM = re.compile(r"[Ա-Ֆա-և]")


def esc(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def styled(text: str, style: str) -> str:
    out = f't("{esc(text)}")'
    if "i" in style:
        out = f"emph({out})"
    if "b" in style:
        out = f"strong({out})"
    return out


def find_anchor(plain: str, surface: str) -> int:
    """First occurrence of surface at Armenian word boundaries."""
    start = 0
    while True:
        pos = plain.find(surface, start)
        if pos < 0:
            return -1
        before = plain[pos - 1] if pos > 0 else " "
        after = plain[pos + len(surface)] if pos + len(surface) < len(plain) else " "
        if not ARM.match(before) and not ARM.match(after):
            return pos
        start = pos + 1


def block_nodes(blk: Block, glosses: list[dict],
                footnotes: dict[str, str]) -> str:
    """Emit typst content code for one block's runs + gloss anchors."""
    runs = md_runs(blk.md)
    plain = "".join(t for t, _ in runs)
    # anchor spans: (start, end, row), non-overlapping, sorted
    spans = []
    for row in glosses:
        pos = find_anchor(plain, row["surface"])
        if pos < 0:
            print(f"WARN: anchor {row['surface']!r} not found "
                  f"in block {row['block_id']}")
            continue
        spans.append((pos, pos + len(row["surface"]), row))
    spans.sort()
    for (s1, e1, r1), (s2, e2, r2) in zip(spans, spans[1:]):
        if e1 > s2:
            print(f"WARN: overlapping anchors {r1['surface']}/"
                  f"{r2['surface']} in block {r1['block_id']}")

    # drop overlapping spans (first wins) so the walker stays linear
    kept = []
    for sp in spans:
        if kept and sp[0] < kept[-1][1]:
            print(f"WARN: overlapping anchor {sp[2]['surface']!r} "
                  f"dropped in block {sp[2]['block_id']}")
            continue
        kept.append(sp)
    spans = kept

    # linear walk over runs; a gloss span may cross style-run
    # boundaries (intra-word style change, styled MWE) — its pieces
    # are collected and emitted as one gl() with mixed styling
    parts: list[str] = []
    pos = 0  # plain-text offset of current run start
    span_i = 0
    pieces: list[str] = []  # styled fragments of the open span

    for text, style in runs:
        if style == "marker":
            num = re.match(r"\[\^(\d+)\]", text).group(1)
            note = footnotes.get(num, "")
            parts.append(f'footnote(t("{esc(note)}"))')
            pos += len(text)
            continue
        cur = 0
        while cur < len(text):
            if span_i >= len(spans):
                parts.append(styled(text[cur:], style))
                cur = len(text)
                continue
            s, e, row = spans[span_i]
            if pos + cur < s:
                stop = min(len(text), s - pos)
                parts.append(styled(text[cur:stop], style))
                cur = stop
                continue
            piece_end = min(e - pos, len(text))
            pieces.append(styled(text[cur:piece_end], style))
            cur = piece_end
            if pos + cur >= e:
                word = " + ".join(pieces)
                pieces = []
                prior = "true" if row["source"] == "prior" else "false"
                parts.append(f'gl({word}, "{esc(row["ru"])}", '
                             f'prior: {prior})')
                span_i += 1
        pos += len(text)
    return " + ".join(p for p in parts if p) if parts else 't("")'


PREAMBLE = """\
// generated by interlinear/render.py — do not edit
#set page(paper: "{paper}", margin: (x: 1.6cm, y: 1.7cm), numbering: "1")
#set text(font: ("{font}", "DejaVu Sans"), size: {size}pt, lang: "hy")
// CONSTANT line spacing: the gloss box is clamped to one text line
// (height 1em, baseline restored), so a glossed line is exactly as
// tall as a plain one; the label overflows into the interline gap.
// The single global leading below is the slimmest that clears the
// hanging labels — every line gets it, glossed or not.
#set par(justify: true, leading: 0.8em, spacing: 1.0em)
#let t(s) = s
#let gl(word, tr, prior: false) = context {{
  let w = if prior {{ underline(stroke: (paint: luma(35%),
    thickness: 0.6pt, dash: "dashed"), offset: 1.6pt, word) }}
    else {{ word }}
  let lbl = text(size: 0.58em, fill: luma(38%), weight: "regular",
                 style: "normal", tr)
  let ww = measure(w).width
  let ts = measure(lbl)
  // gloss may overhang only ~0.4em per side: larger overhangs made
  // neighbor glosses nearly touch and visually drift onto the next
  // word (2026-07-23 editorial pass)
  let bw = calc.max(ww, ts.width - 0.8em.to-absolute())
  box(width: bw, height: 1em, baseline: 0.25em, align(center,
    stack(dir: ttb, spacing: 0.24em,
      w,
      align(center, box(width: 0pt, height: 0pt,
        place(center, box(width: ts.width, lbl)))))))
}}
#let bookheading(body) = align(center,
  text(weight: "bold", size: 1.2em, body))
"""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--book", required=True)
    ap.add_argument("--chunk", required=True)
    ap.add_argument("--paper", default="a5")
    ap.add_argument("--size", default="10")
    ap.add_argument("--font", default="FreeSerif")
    ap.add_argument("--no-compile", action="store_true")
    ap.add_argument("--glosses", default="glosses.tsv",
                    help="gloss table to render (e.g. glosses_expanded.tsv)")
    args = ap.parse_args()
    out_dir = HERE / args.book / args.chunk

    blocks = parse_book_md(out_dir / "book.md")
    with (out_dir / args.glosses).open(encoding="utf-8") as f:
        rows = list(csv.DictReader(f, delimiter="\t"))
    by_block: dict[str, list[dict]] = {}
    for r in rows:
        by_block.setdefault(r["block_id"], []).append(r)

    # footnote blocks: id -> text (typst places them itself)
    footnotes: dict[str, str] = {}
    for blk in blocks:
        if blk.kind == "footnote":
            m = re.match(r"\[\^(\d+)\]:\s*(.*)", blk.md, re.S)
            if m:
                fn_runs = md_runs(m.group(2))
                footnotes[m.group(1)] = "".join(t for t, _ in fn_runs)

    lines = [PREAMBLE.format(paper=args.paper, size=args.size,
                             font=args.font)]
    for blk in blocks:
        if blk.kind == "footnote":
            continue
        code = block_nodes(blk, by_block.get(f"{blk.id:04d}", []),
                           footnotes)
        if blk.kind == "heading":
            lines.append(f"#bookheading[#{{{code}}}]")
        else:
            lines.append(f"#par(first-line-indent: 0em)[#h(1.2em)"
                         f"#{{{code}}}]")
        lines.append("")

    typ = out_dir / "book.typ"
    typ.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {typ}")
    if not args.no_compile:
        pdf = out_dir / "book.pdf"
        res = subprocess.run(["typst", "compile", str(typ), str(pdf)],
                             capture_output=True, text=True)
        if res.returncode:
            print(res.stderr)
            return 1
        print(f"compiled {pdf}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
